scene.onOverlapTile(SpriteKind.Player, sprites.castle.rock1, function (sprite33, location33) {
    tiles.setCurrentTilemap(tilemap`level11`)
    tiles.placeOnTile(Fantasma, tiles.getTileLocation(2, 12))
    info.changeScoreBy(1)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    enemigo(1, 13, 85)
    enemigo(5, 13, 85)
    enemigo(8, 13, 85)
    enemigo(19, 11, 85)
    enemigo(23, 11, 85)
    enemigo(26, 11, 85)
    enemigo(30, 11, 85)
    enemigo(35, 11, 85)
    enemigo(41, 11, 85)
    enemigo(46, 11, 85)
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.rock0, function (sprite3, location3) {
    tiles.setCurrentTilemap(tilemap`level17`)
    tiles.placeOnTile(Fantasma, tiles.getTileLocation(1, 13))
    info.changeScoreBy(1)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    enemigo(13, 13, 75)
    enemigo(14, 13, 75)
    enemigo(16, 13, 75)
    enemigo(30, 13, 75)
    enemigo(32, 13, 75)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite7, otherSprite) {
    if (Fantasma.x == 10) {
        sprites.destroy(Fantasma, effects.disintegrate, 500)
        info.changeScoreBy(1)
    } else {
        info.changeLifeBy(-1)
        scene.cameraShake(4, 500)
        pause(1000)
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile5`, function (sprite32, location32) {
    tiles.setCurrentTilemap(tilemap`level10`)
    tiles.placeOnTile(Fantasma, tiles.getTileLocation(38, 10))
    info.changeScoreBy(1)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    enemigo(16, 10, 90)
    enemigo(19, 10, 90)
    enemigo(23, 10, 90)
    enemigo(6, 8, 90)
    enemigo(10, 8, 90)
    enemigo(14, 8, 90)
    enemigo(17, 8, 90)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestOpen, function (sprite2, location2) {
    tiles.setCurrentTilemap(tilemap`level13`)
    tiles.placeOnTile(Fantasma, tiles.getTileLocation(1, 12))
    info.changeScoreBy(1)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    enemigo(9, 13, 75)
    enemigo(5, 13, 75)
    enemigo(22, 12, 75)
    enemigo(41, 11, 75)
    enemigo(43, 11, 75)
    enemigo(44, 11, 75)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava0, function (sprite, location) {
    scene.cameraShake(4, 500)
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleBlueCrystal, function (sprite4, location4) {
    tiles.setCurrentTilemap(tilemap`level0`)
    tiles.placeOnTile(Fantasma, tiles.getTileLocation(3, 8))
    info.changeScoreBy(1)
    enemigo(3, 15, 75)
    enemigo(18, 15, 75)
    enemigo(23, 15, 75)
    enemigo(24, 9, 75)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    Fantasma.setImage(img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fdddddd111df......
        ......fbddddddd1df......
        ......ffbbddbfd1df......
        .......fcbbdcfddbf......
        .......fffbddccffff.....
        .......ffffcfbbb1bcf....
        ......ffffffffcd1b1f....
        ...ffffffffff..fdfdf....
        .....ffffff.....f.f.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    Fantasma.setImage(img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f1111111dbf......
        ......fd1111111ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd111ddddddf......
        ......fd1dddddddbf......
        ......fd1dfbddbbff......
        ......fbddfcdbbcf.......
        .....ffffccddbfff.......
        ....fcb1bbbfcffff.......
        ....f1b1dcffffffff......
        ....fdfdf..ffffffffff...
        .....f.f.....ffffff.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite6, location6) {
    scene.cameraShake(4, 500)
    info.changeLifeBy(-1)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Fantasma.isHittingTile(CollisionDirection.Bottom)) {
        Fantasma.vy = -150
        music.play(music.createSoundEffect(WaveShape.Sine, 5000, 67, 51, 255, 303, SoundExpressionEffect.Tremolo, InterpolationCurve.Curve), music.PlaybackMode.UntilDone)
    }
})
function enemigo (col: number, fil: number, vel: number) {
    Enemigo = sprites.create(img`
        . . . . . b b b b b b . . . . . 
        . . . b b 9 9 9 9 9 9 b b . . . 
        . . b b 9 9 9 9 9 9 9 9 b b . . 
        . b b 9 d 9 9 9 9 9 9 9 9 b b . 
        . b 9 d 9 9 9 9 9 1 1 1 9 9 b . 
        b 9 d d 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 d 9 9 9 9 9 9 1 1 1 9 9 9 b 
        b 9 3 9 9 9 9 9 9 9 9 9 1 9 9 b 
        b 5 3 d 9 9 9 9 9 9 9 9 9 9 9 b 
        b 5 3 3 9 9 9 9 9 9 9 9 9 d 9 b 
        b 5 d 3 3 9 9 9 9 9 9 9 d d 9 b 
        . b 5 3 3 3 d 9 9 9 9 d d 5 b . 
        . b d 5 3 3 3 3 3 3 3 d 5 b b . 
        . . b d 5 d 3 3 3 3 5 5 b b . . 
        . . . b b 5 5 5 5 5 5 b b . . . 
        . . . . . b b b b b b . . . . . 
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Enemigo, tiles.getTileLocation(col, fil))
    Enemigo.setBounceOnWall(true)
    Enemigo.setVelocity(vel, 0)
}
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardWater, function (sprite5, location5) {
    scene.cameraShake(4, 500)
    info.changeLifeBy(-1)
})
let Enemigo: Sprite = null
let Fantasma: Sprite = null
Fantasma = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
info.setLife(3)
info.setScore(0)
controller.moveSprite(Fantasma, 100, 0)
tiles.setCurrentTilemap(tilemap`level1`)
tiles.placeOnTile(Fantasma, tiles.getTileLocation(1, 12))
scene.cameraFollowSprite(Fantasma)
Fantasma.ay = 210
